version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app/frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
